version: ~> 1.0

language: scala

env:
  - TRAVIS_JDK=8
  - TRAVIS_JDK=11

global:
  # encrypt with: travis encrypt --pro BINTRAY_USER=...
  - secure: "TYv7WiEXuF4lELHl8H1L3YIhXG0prIWyWMaEmm5wNOKupwuZ2lOKuT4OdSWxqoPjDU9SneDocJYjsodIpSTVlr8cCDIb5Wx2UE9ar07kL1BtOa1pGZdcUIB2UuckQbvR2SCnYn1uFYWxi73AHxX+QGFYF8us7G3Ltbapy1ZID3dVkFJRsF86+VzwQ+lM9owsgz9nDiPDzlxDZ3sZcNbd92nT1Z/LllaTuntSPCMttWR2QrWTFuu3Aa77PbIEtmc23SLWaqtLyHWDXlmSo63LsFHv88qLF7DDRN0khqGKptnAS6F9+DIpGgO+ZIrbuVk7Uu2ji3YyjM/ISOnct+3/h39BGTbVUYPKWx41iD8HiwSZ24/0xE91ywwm9Jq/yVLkAtPJ2NCS0zP/9jbu8K7O9BVyre4QA3VJ2mXMlrWj6CSgl1igLkGdfEI8UNkOm+CbEZfPTQv1XbNRj5vI9zL4bRGVOZvxkFK8FtmsaXEDByWk5slcf5u3+o0Q60CQSTXQ9rQgtovSq3brJbIPBEFlTu0O1sPzg5L33G6fkLeXpw2PaWi5ouyCDmMbNgKGnT9i5c51gj3/sgcoAKtc9KK7z3yPaDurTDhJL1tv4W9iIJCQ+YSPuEYmj6ZCtQ9Ni1HC6dZSmh5XzvuOZ73GlV1GYGL/K67LYmA1mPfVaPDPCDQ="

  # encrypt with: travis encrypt --pro BINTRAY_PASS=...
  - secure: "SbxN0f2s68e4RphfZPHWVX6RnOQfKW9DD0ALCW7sPh1oEMf3cY58rMCGIxFjrHxK+smYAERXWqFK1w6e0KGPXQ+FknWDY7zfGQO8xkI9EiIxZfdw91usibgiCD4UNKRdK/v6RydVKHo4R1Vh9GnCqo2zTGvnLEyRK1GKYaM9eEzeW/nukHrsgV/zDWEbANm9LINFiPP1PvUnEJEl0AyZx6aMi/Q04ZJ8BBUwQ09Z1xIQYzon65iDgR9IxEBxpjSuzOwwmEtu0kAKvDLPJLww4cp9+3Bpd6BdQOJaG4a1d0/f913dX29xltyfiHOv/f9AE/smcvrbUNieLRp2fmv1mfEDgOjrHvzQlYYV+Vb8B1un9WMQPTVp6PFcY6BhJOekVfaFyQiXniyLg9YUG4rgqVb/l0Uk47p1jAhG2ePoghog6EDeGXgMG77oywo/aioTznQp689UALc+jcEIzXaO5EPKjxkftQbuLuw63l3XB1ka08LYHHz+fep+/egKVqqOFQVvXTwE9AQT3A8psrTNx9nArwovspcuWgppd6moXBon/oOspCSWNa7BkgodvQpatNUm3PYj/NeBGhWd2W7WIIB52BDbT6/YU5rpDLbGFWSAAw90YZMFlD5K7Xsn51Qqzm2YEmqwzI9XHzgQEcmHMgyPfB8lUKw3M9R9CK7aqYQ="

before_install:
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.2/install.sh | bash && . ~/.jabba/jabba.sh

install:
  - jabba install $(jabba ls-remote "adopt@~1.$TRAVIS_JDK.0-0" --latest=patch) && jabba use "$_" && java -Xmx32m -version


script:
  - cd docs && sbt test

jobs:
  include:
    - stage: jacoco
      script: sbt +jacoco
      env: TRAVIS_JDK=8
      name: "Jacoco JDK8"
    - env: TRAVIS_JDK=11
      name: "Jacoco JDK11"
      script: sbt +jacoco

    - stage: test

    - script: sbt +mimaReportBinaryIssues
      name: "Validations JDK 8"
      env: TRAVIS_JDK=8
    - script: sbt +mimaReportBinaryIssues
      name: "Validations JDK11"
      env: TRAVIS_JDK=11
    - script: sbt +publishLocal +plugin/test +plugin/scripted
      name: "Test plugins JDK 8"
      env: TRAVIS_JDK=8
    - script: sbt +publishLocal +plugin/test +plugin/scripted
      name: "Test plugins JDK11"
      env: TRAVIS_JDK=11
    - script: cd docs && sbt validateDocs evaluateSbtFiles
      name: "Validate docs, Evaluate sbt files JDK 8"
      env: TRAVIS_JDK=8
    - script: cd docs && sbt validateDocs evaluateSbtFiles
      name: "Validate docs, Evaluate sbt files JDK 11"
      env: TRAVIS_JDK=11

    - stage: deploy
      name: "Publish artifacts to Bintray"
      script: sbt +publish
      env: TRAVIS_JDK=11

stages:
  - name: jacoco
  - name: test
  - name: deploy
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

after_success: bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.coursier/cache
    - $HOME/.ivy2/cache
    - $HOME/.jabba/jdk
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete


branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

#notifications:
#  webhooks:
#    urls: https://webhooks.gitter.im/e/d2c8a242a2615f659595
#    on_success: always
#    on_failure: always
